id: P006904
initial_creation_type: ocr
source_metadata:
  id: bdr:W22183
  title: འབྲུག་ཟངས་དཀར་གྱི་བླ་མ་བཞད་པ་རྡོ་རྗེ་དང་ཀརྨ་བསྟན་འཛིན། ངག་དབང་ཚེ་རིང་གསུམ་གྱི་གསུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    596c645205354aeb8380a6a7a6dc6fa8:
      image_group_id: I2229
      title: ''
      volume_number: 1
      total_pages: 360
