id: opecha:P006904
initial_creation_type: ocr
source_metadata:
  id: bdr:W22183
  title: འབྲུག་ཟངས་དཀར་གྱི་བླ་མ་བཞད་པ་རྡོ་རྗེ་དང་ཀརྨ་བསྟན་འཛིན། ངག་དབང་ཚེ་རིང་གསུམ་གྱི་གསུང་ཕྱོགས་བསྒྲིགས།
  volume: ''
  author: ''
