id: I4A5EBD09
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:40:34+00:00'
last_modified: '2022-06-08T09:30:11.446012+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22183
  title: འབྲུག་ཟངས་དཀར་གྱི་བླ་མ་བཞད་པ་རྡོ་རྗེ་དང་ཀརྨ་བསྟན་འཛིན། ངག་དབང་ཚེ་རིང་གསུམ་གྱི་གསུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AC58:
      image_group_id: I2229
      title: ''
      total_pages: 360
      order: 1
      base_file: AC58.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
